# Generated by Django 2.1.3 on 2018-11-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_manage', '0002_auto_20181119_0947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentstudyrecord',
            unique_together={('student', 'classstudyrecord')},
        ),
    ]
