# Generated by Django 2.1.3 on 2018-11-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181115_1130'),
        ('student_manage', '0003_auto_20181119_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classstudyrecord',
            unique_together={('class_obj', 'day_num')},
        ),
    ]
