# Generated by Django 2.1.3 on 2018-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181115_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='positions',
            field=models.ManyToManyField(to='app01.Position'),
        ),
    ]
