# Generated by Django 2.1.3 on 2018-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181115_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deal_date',
            field=models.DateField(default='2012-12-12', null=True),
        ),
    ]
