# Generated by Django 2.1.3 on 2018-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20181120_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='deal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
