# Generated by Django 2.1.3 on 2018-11-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='Positions',
            new_name='positions',
        ),
    ]
