# Generated by Django 2.1.3 on 2018-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181115_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_id',
            field=models.CharField(default='暂无', max_length=32, verbose_name='菜单id名'),
        ),
    ]
