# Generated by Django 2.1.3 on 2018-11-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20181119_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classify', to='rbac.Menu', verbose_name='url分类'),
        ),
    ]
