# Generated by Django 2.1.3 on 2018-11-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20181119_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=60, verbose_name='权限'),
        ),
    ]
