# Generated by Django 2.1.3 on 2018-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20181119_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='related_name',
            field=models.CharField(max_length=32, null=True, verbose_name='别名'),
        ),
    ]
